"""empty message

Revision ID: 1903d426e359
Revises: 8a714413b3a3
Create Date: 2024-09-14 14:36:06.478273

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1903d426e359'
down_revision = '8a714413b3a3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('news', schema=None) as batch_op:
        batch_op.add_column(sa.Column('category', sa.String(length=50), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('news', schema=None) as batch_op:
        batch_op.drop_column('category')

    # ### end Alembic commands ###
