"""create comments table

Revision ID: 5ac332efb5e3
Revises: 1075ad3d3623
Create Date: 2024-11-02 17:10:01.697007

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '5ac332efb5e3'
down_revision = '1075ad3d3623'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('comments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('article_id', sa.Integer(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('author', sa.String(length=100), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['article_id'], ['news.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('tags', schema=None) as batch_op:
        batch_op.drop_constraint('tags_ibfk_1', type_='foreignkey')
        batch_op.drop_column('article_id')
        batch_op.drop_column('content')
        batch_op.drop_column('author')
        batch_op.drop_column('created_at')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tags', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_at', mysql.DATETIME(), nullable=True))
        batch_op.add_column(sa.Column('author', mysql.VARCHAR(length=100), nullable=False))
        batch_op.add_column(sa.Column('content', mysql.TEXT(), nullable=False))
        batch_op.add_column(sa.Column('article_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False))
        batch_op.create_foreign_key('tags_ibfk_1', 'news', ['article_id'], ['id'])

    op.drop_table('comments')
    # ### end Alembic commands ###
